from __future__ import annotations

LEAP0_API_KEY_ENV = "LEAP0_API_KEY"

LEAP0_BASE_URL_ENV = "LEAP0_BASE_URL"

LEAP0_SANDBOX_DOMAIN_ENV = "LEAP0_SANDBOX_DOMAIN"

LEAP0_SDK_OTEL_ENABLED_ENV = "LEAP0_SDK_OTEL_ENABLED"

OTEL_EXPORTER_OTLP_ENDPOINT_ENV = "OTEL_EXPORTER_OTLP_ENDPOINT"

OTEL_EXPORTER_OTLP_HEADERS_ENV = "OTEL_EXPORTER_OTLP_HEADERS"
